### ISSUE TITLE
Implementing new class Gender

### ISSUE THREAD

**Issue by fr4nk** [DiUS/java-faker#468]
**Faking gender ist not implemented**
Random gender can be used to 'genderify' first names (or even last name in languages like russian).
Was once requested in issue #383 

**Solution: implement the missing class Gender**
The needed yaml file is already there.

I'm happy to take the challenge.

**Comment by fr4nk** [comment]
YAML looks like this:

```yaml
en:
  faker:
    gender:
      types: ["Female", "Male", "Non-binary", "Agender", "Genderfluid", "Genderqueer", "Bigender", "Polygender"]
      binary_types: ["Female", "Male"]
```
So I would implement methods `String type()` and `String binaryType()`.
