### ISSUE TITLE
Faker should allow loading external yml files

### ISSUE THREAD

**Issue by daniel-frak** [DiUS/java-faker#489]
**Is your feature request related to a problem? Please describe.**
I'm trying to extend Faker to generate some domain-specific data using yml files.
The only solution to this is proposed in #255. Unfortunately, that solution is only a hack and I consider it bad code. I should not have to hijack locale to inject my own definitions and I should be able to load more than one yml file.

The main problem seems to lie in `FakeValuesService` which, for English, completely skips loading external files (relying on a predefined, non-changeable list) and for other languages only loads a single file via FakeValues.

**Describe the solution you'd like**
Faker should always dynamically find all yml files or, at the very least, there should be an option for passing (multiple) additional files through the constructor.

**Describe alternatives you've considered**
The only alternative seems to be the lackluster solution proposed in #255.

**Additional context**

Not all data is going to be useful to the general public and not all data can be shared with the general public due to company policies. While the library is immensely useful, a single yml file (and broken locale) is not enough to ensure clean and maintainable code in projects using it.

**Comment by schallerala** [comment]
I partly agree with you. That the control around additional files is a bit lacunar, as it is hard-coded, and also only for the _root_ English Locale.

However, you aren't constrained to use the Faker class as is. You could extend it, and extend its _provider_ to resolve a new key that you would declare in your Yaml file.

Faker extension:
---
```java
public class Faker extends com.github.javafaker.Faker {
    /** Extended {@link com.github.javafaker.Name} class. */
    private final Name name;
    private final ProviderX providerX;

    // Initialize those in the constructor(s) 
    // where you call the super class constructor

    @Override
    public Name name() {
        return this.name;
    }
    // ...
}
```

Name _provider_ extension:
---
```java
public class Name extends com.github.javafaker.Name {

    private final Faker faker;
    protected Name(Faker faker) {
        super(faker);
        this.faker = faker;
    }

    @Override
    public String firstName() {
        return this.faker.bool().bool() ? super.firstName() :
                this.faker.bool().bool() ? this.accentuatedFirstName() :
                        this.accentuatedMultipleFirstName();
    }

    public String accentuatedFirstName () {
        // custom key
        return this.faker.resolve("name.accentuated_first_name");
    }
    // ...
}
```

My local Yaml file:
---
```yaml
fr-CH:
    # if a field isn't found in this file, it falls back on the fr.yml, and 
    # then english (en.yml and other direct files)
    faker:
        name:
            accentuated_first_name: [Fédéric, Mélissa, Sébastien, Désiré, Hervé, Raphël, Noël, Jérôme, Joël, 'Jean-Louis', 'Jean-Pierre', François, Léa, Cédric, Céline]

        provider_x:
            a: [1, 2, 3, 4, 5, 6]
            # you get it
```
