### ISSUE TITLE
Coherent fake object support

### ISSUE THREAD

**Issue by jvmlet** [DiUS/java-faker#600]
It's impossible to generate the  fake object with coherent fields 
Consider below `yml` file :

```yml
en:
  faker:
    operating_system:
      win:
        name:
          - Windows
        version:
          - Vista
          - 7
          - 8
          - 10
      android:
        name :
          - Android
        version:
          - Pie
          - Loolilop
      any:
        - "#{win}"
        - "#{android}"
 ```

it would be great to be able to have :

```java
@Getter @Setter
class OpertingSysytemPojo {
 private String name;
 private String version;
}
...
OpertingSysytemPojo os =  faker.operatingSystem().any().bind(OpertingSysytemPojo.class)
```
