### ISSUE TITLE
zh_CN.yaml does not really fit Chinese people's habits

### ISSUE THREAD

**Issue by teddyxlandlee** [DiUS/java-faker#646]
Here's an example:  
```yaml
    university:
      prefix: ["东", "南", "西", "北", "东南", "东北", "西南", "西北", "中国"]
      suffix: ["理工大学", "技术大学", "艺术大学", "体育大学", "经贸大学", "农业大学", "科技大学", "大学"]
      name:
        - "#{University.prefix}#{University.suffix}"
```  
There is not any university called "东理工大学" (east university of science and engineering) or "中国大学" (university of China). Maybe you need more samples, instead of mixing these simple prefixes and suffixes above.  

Besides, I've seen that you use hundreds of samples for Chinese names. In fact, Chinese people born in different ages might have different features in their names. Like 1950s sometimes may be named after "红军" (the Red Army) or "建国" (state foundation), while 2010s are probably named after "浩轩", "静涵", etc. It is awful to simply pile up Chinese name samples like "Jack", "Cindy" or "Tony" in English, or "Müller", "Hans" in German.

What's more, Chinese postcodes have its own rule. Codes like "999999" is invalid in China.

I wonder that ruby faker is not the god of this project. You can enhance your own standard if required.
